# Generated by Django 6.0.7 on 2026-08-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_taskcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcheck',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcheck',
            name='manual_complete',
            field=models.BooleanField(default=False),
        ),
    ]
