# Generated by Django 6.0.7 on 2026-08-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_taskcheck_is_manual_taskcheck_manual_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTaskCheck',
            fields=[
            ],
            options={
                'verbose_name': 'Manual Task',
                'verbose_name_plural': 'Manual Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cards.taskcheck',),
        ),
    ]
