services:
  flask_app:
    build: ./app
    #restart: unless-stopped
    environment:
      - DB_HOST=10.1.10.243
      - DB_USER=root
      - DB_PASSWORD=topSecretPassword#1!
      - DB_NAME=jarvis_knowledge_matrix
      - FLASK_SECRET_KEY=reactorArchIsLife
      - API_ENDPOINT=http://10.1.40.143/api
      - API_KEY=starklab-api-key-2026
    ports:
      - 80:5000