services:
  flask_app:
    build: ./app
    #restart: unless-stopped
    environment:
      - DB_HOST=129.21.220.95
      - DB_USER=root
      - DB_PASSWORD=topSecretPassword#1!
      - DB_NAME=jarvis_knowledge_matrix
      - FLASK_SECRET_KEY=reactorArchIsLife
      - API_ENDPOINT=http://<ip>/api
      - API_KEY=starklab-api-key-2026
    ports:
      - 8080:5000