# Generated by Django 6.0.7 on 2026-07-30 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countdown_minutes', models.IntegerField(default=60)),
                ('is_running', models.BooleanField(default=False)),
                ('countdown_start', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Game Settings',
            },
        ),
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Unknown', max_length=50)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_total', models.IntegerField(default=0)),
                ('manual_override', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='cards.card')),
            ],
        ),
    ]
