# Generated by Django 6.0.7 on 2026-07-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_gamesettings_countdown_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='intrusion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentstatus',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.cardstatus'),
        ),
    ]
