# Generated by Django 6.0.7 on 2026-07-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_gamesettings_intrusion_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='mission_accomplished',
            field=models.BooleanField(default=False),
        ),
    ]
