# Generated by Django 6.0.7 on 2026-07-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_gamesettings_mission_accomplished'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='intrusion_applied',
            field=models.BooleanField(default=False),
        ),
    ]
